# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    # Integrates node.js
    - name: Install Node.js
      uses: actions/setup-node@v4
      with: 
        node-version: '22'

      # Install Newman
      - name: Install Newman
      - run: npm Install Newman -g
    
      #  Rum Neman test
        - name: Running first collection
          run: newman run AE_API_Test.postman_collection.json &

      # Run Newman Test #2
      - name: Running ccollection with environment
        run: newman run  AE_API_Test.postman_collection.json -e ev.postman_environment.json
